=== westerly-lzh/x12-parser/bin/mapping/map.xsd
<?xml version="1.0"?><!--
######################################################################
# Copyright (c)
#   John Holland <john@zoner.org>
# All rights reserved.
#
# This software is licensed as described in the file LICENSE.txt, which
# you should have received as part of this distribution.
#
######################################################################
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
    XML Schema for pyx12 data validation maps
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="transaction" type="transactionType"/>

  <xsd:complexType name="transactionType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="loop" type="LoopType"/>
    </xsd:sequence>
    <xsd:attribute name="xid" type="xsd:NMTOKEN" use="required"/>
  </xsd:complexType>

    <!-- A loop can contain multiple segments and multiple child loops -->
    <xsd:complexType name="LoopType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="usage" type="usageType"/>
      <xsd:element name="pos" type="xsd:nonNegativeInteger"/>
      <xsd:element name="repeat" type="xsd:token"/>
      <xsd:group ref="LoopChildGroupType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="xid" type="xsd:NMTOKEN" use="required"/>
    <xsd:attribute name="pos" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="usage" type="usageType"/>
    <xsd:attribute name="repeat" type="xsd:token"/>
    <xsd:attribute name="type" type="xsd:NMTOKEN"/>
  </xsd:complexType>
  
  <xsd:group id="LoopChildGroupType" name="LoopChildGroupType">
    <xsd:choice>
      <xsd:element name="segment" type="SegmentType"/>
      <xsd:element name="loop" type="LoopType"/>
    </xsd:choice>
  </xsd:group>

    <!-- Segments can contain both simple elements and composite elements -->
    <xsd:group id="SegmentChildGroupType" name="SegmentChildGroupType">
    <xsd:choice>
      <xsd:element name="element" type="ElementType"/>
      <xsd:element name="composite" type="CompositeType"/>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="SegmentType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="end_tag" type="xsd:token" minOccurs="0"/>
      <xsd:element name="usage" type="usageType"/>
      <xsd:element name="pos" type="xsd:nonNegativeInteger"/>
      <xsd:element name="max_use" type="xsd:token"/>
      <xsd:element name="syntax" type="syntaxType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:group ref="SegmentChildGroupType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="xid" type="xsd:NMTOKEN" use="required"/>
    <xsd:attribute name="usage" type="usageType"/>
    <xsd:attribute name="pos" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="max_use" type="xsd:token"/>
  </xsd:complexType>

  <xsd:complexType name="CompositeType">
    <xsd:sequence>
      <xsd:element name="data_ele" type="xsd:token"/>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="usage" type="usageType"/>
      <xsd:element name="seq" type="xsd:nonNegativeInteger"/>
      <xsd:element name="refdes" type="xsd:token" minOccurs="0"/>
      <xsd:element name="syntax" type="syntaxType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="repeat" type="xsd:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="element" type="ElementType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="xid" type="xsd:NMTOKEN"/>
    <xsd:attribute name="data_ele" type="xsd:token"/>
    <xsd:attribute name="usage" type="usageType"/>
    <xsd:attribute name="seq" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>

  <xsd:complexType name="ElementType">
    <xsd:sequence>
      <xsd:element name="data_ele" type="xsd:token"/>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="usage" type="usageType"/>
        <!-- IG usage, -->
        <xsd:element name="seq" type="xsd:nonNegativeInteger"/>
      <xsd:element name="refdes" type="xsd:token" minOccurs="0"/>
      <xsd:element name="repeat" type="xsd:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="valid_codes" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="code" type="xsd:token" minOccurs="0" maxOccurs="unbounded"/>
          </xsd:sequence>
          <xsd:attribute name="external" type="xsd:NMTOKEN"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="regex" type="xsd:token" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="xid" type="xsd:NMTOKEN" use="required"/>
    <xsd:attribute name="data_ele" type="xsd:token"/>
    <xsd:attribute name="name" type="xsd:token"/>
    <xsd:attribute name="usage" type="usageType"/>
      <!-- IG usage, -->
      <xsd:attribute name="seq" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:simpleType name="formatType">
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="D8"/>
        <!-- Date CCYYMMDD -->
        <xsd:enumeration value="D6"/>
        <!-- Date YYMMDD -->
        <xsd:enumeration value="RD8"/>
        <!-- Date Range CCYYMMDD-CCYYMMDD -->
        <xsd:enumeration value="TM"/>
        <!-- Time HHMM -->
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="usageType">
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="R"/>
        <!-- Required -->
        <xsd:enumeration value="S"/>
        <!-- Situational -->
        <xsd:enumeration value="N"/>
        <!-- Not Used -->
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="syntaxType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value='(E|L|P|C|R)([0-9]{2}){2,20}'/>
        <!-- Syntax Codes:
          P - Paired or Multiple - If any element specified is present, all must be present
          R - Required - At least one must be present
          E - Exclusion - Not more than one specified element may be present
          C - Conditional - If first is present, all others must be present
          L - List - If first is present, at least one other must be present
        -->
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== westerly-lzh/x12-parser/bin/mapping/277.5010.X214.xml
<?xml version="1.0"?><!--
######################################################################
# Copyright (c) SWMBH
#   John Holland <john@zoner.org>
# All rights reserved.
#
# This software is licensed as described in the file LICENSE.txt, which
# you should have received as part of this distribution.
#
######################################################################
-->
<transaction xid="277" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
  <name>HIPAA Health Care Claim Acknowledgement X214-277</name>
  <loop xid="ISA_LOOP" type="explicit">
    <name>Interchange Control Header</name>
    <usage>R</usage>
    <pos>0010</pos>
    <repeat>&gt;1</repeat>
    <segment xid="ISA">
      <name>Interchange Control Header</name>
      <usage>R</usage>
      <pos>0100</pos>
      <max_use>1</max_use>
      <element xid="ISA01">
        <data_ele>I01</data_ele>
        <name>Authorization Information Qualifier</name>
        <usage>R</usage>
        <seq>01</seq>
        <valid_codes>
          <code>00</code>
          <code>03</code>
        </valid_codes>
      </element>
      <element xid="ISA02">
        <data_ele>I02</data_ele>
        <name>Authorization Information</name>
        <usage>R</usage>
        <seq>02</seq>
      </element>
      <element xid="ISA03">
        <data_ele>I03</data_ele>
        <name>Security Information Qualifier</name>
        <usage>R</usage>
        <seq>03</seq>
        <valid_codes>
          <code>00</code>
          <code>01</code>
        </valid_codes>
      </element>
      <element xid="ISA04">
        <data_ele>I04</data_ele>
        <name>Security Information</name>
        <usage>R</usage>
        <seq>04</seq>
      </element>
      <element xid="ISA05">
        <data_ele>I05</data_ele>
        <name>Interchange Sender ID Qualifier</name>
        <usage>R</usage>
        <seq>05</seq>
        <valid_codes>
          <code>01</code>
          <code>14</code>
          <code>20</code>
          <code>27</code>
          <code>28</code>
          <code>29</code>
          <code>30</code>
          <code>33</code>
          <code>ZZ</code>
        </valid_codes>
      </element>
      <element xid="ISA06">
        <data_ele>I06</data_ele>
        <name>Interchange Sender ID</name>
        <usage>R</usage>
        <seq>06</seq>
      </element>
      <element xid="ISA07">
        <data_ele>I05</data_ele>
        <name>Interchange Receiver ID Qualifier</name>
        <usage>R</usage>
        <seq>07</seq>
        <valid_codes>
          <code>01</code>
          <code>14</code>
          <code>20</code>
          <code>27</code>
          <code>28</code>
          <code>29</code>
          <code>30</code>
          <code>33</code>
          <code>ZZ</code>
        </valid_codes>
      </element>
      <element xid="ISA08">
        <data_ele>I07</data_ele>
        <name>Interchange Receiver ID</name>
        <usage>R</usage>
        <seq>08</seq>
      </element>
      <element xid="ISA09">
        <data_ele>I08</data_ele>
        <name>Interchange Date</name>
        <usage>R</usage>
        <seq>09</seq>
        <valid_codes/>
      </element>
      <element xid="ISA10">
        <data_ele>I09</data_ele>
        <name>Interchange Time</name>
        <usage>R</usage>
        <seq>10</seq>
        <valid_codes/>
      </element>
      <element xid="ISA11">
        <data_ele>I65</data_ele>
        <name>Interchange Control Standards Identifier</name>
        <usage>R</usage>
        <seq>11</seq>
      </element>
      <element xid="ISA12">
        <data_ele>I11</data_ele>
        <name>Interchange Control Version Number</name>
        <usage>R</usage>
        <seq>12</seq>
        <valid_codes>
          <code>00501</code>
        </valid_codes>
      </element>
      <element xid="ISA13">
        <data_ele>I12</data_ele>
        <name>Interchange Control Number</name>
        <usage>R</usage>
        <seq>13</seq>
      </element>
      <element xid="ISA14">
        <data_ele>I13</data_ele>
        <name>Acknowledgment Requested</name>
        <usage>R</usage>
        <seq>14</seq>
        <valid_codes>
          <code>0</code>
          <code>1</code>
        </valid_codes>
      </element>
      <element xid="ISA15">
        <data_ele>I14</data_ele>
        <name>Usage Indicator</name>
        <usage>R</usage>
        <seq>15</seq>
        <valid_codes>
          <code>P</code>
          <code>T</code>
        </valid_codes>
      </element>
      <element xid="ISA16">
        <data_ele>I15</data_ele>
        <name>Component Element Separator</name>
        <usage>R</usage>
        <seq>16</seq>
      </element>
    </segment>
      <!--End of ISA segment-->
      <loop xid="GS_LOOP" type="explicit">
      <name>Functional Group Header</name>
      <usage>R</usage>
      <pos>0200</pos>
      <repeat>&gt;1</repeat>
      <segment xid="GS">
        <name>Functional Group Header</name>
        <usage>R</usage>
        <pos>0100</pos>
        <max_use>1</max_use>
        <element xid="GS01">
          <data_ele>479</data_ele>
          <name>Functional Identifier Code</name>
          <usage>R</usage>
          <seq>01</seq>
          <valid_codes>
            <code>HN</code>
          </valid_codes>
        </element>
        <element xid="GS02">
          <data_ele>142</data_ele>
          <name>Application Sender's Code</name>
          <usage>R</usage>
          <seq>02</seq>
        </element>
        <element xid="GS03">
          <data_ele>124</data_ele>
          <name>Application Receiver's Code</name>
          <usage>R</usage>
          <seq>03</seq>
        </element>
        <element xid="GS04">
          <data_ele>373</data_ele>
          <name>Functional Group Date</name>
          <usage>R</usage>
          <seq>04</seq>
          <valid_codes/>
        </element>
        <element xid="GS05">
          <data_ele>337</data_ele>
          <name>Functional Group Time</name>
          <usage>R</usage>
          <seq>05</seq>
          <valid_codes/>
        </element>
        <element xid="GS06">
          <data_ele>28</data_ele>
          <name>Group Control Number</name>
          <usage>R</usage>
          <seq>06</seq>
        </element>
        <element xid="GS07">
          <data_ele>455</data_ele>
          <name>Responsible Agency Code</name>
          <usage>R</usage>
          <seq>07</seq>
          <valid_codes>
            <code>X</code>
          </valid_codes>
        </element>
        <element xid="GS08">
          <data_ele>480</data_ele>
          <name>Version / Release / Industry Identifier Code</name>
          <usage>R</usage>
          <seq>08</seq>
          <valid_codes>
            <code>005010X214</code>
          </valid_codes>
        </element>
      </segment>
          <!--End of GS segment-->
          <loop xid="ST_LOOP" type="explicit">
        <name>Transaction Set Header</name>
        <usage>R</usage>
        <pos>0200</pos>
        <repeat>&gt;1</repeat>
        <segment xid="ST">
          <name>Transaction Set Header</name>
          <usage>R</usage>
          <pos>0050</pos>
          <max_use>1</max_use>
          <element xid="ST01">
            <data_ele>143</data_ele>
            <name>Transaction Set Identifier Code</name>
            <usage>R</usage>
            <seq>01</seq>
            <valid_codes>
              <code>277</code>
            </valid_codes>
          </element>
          <element xid="ST02">
            <data_ele>329</data_ele>
            <name>Transaction Set Control Number</name>
            <usage>R</usage>
            <seq>02</seq>
          </element>
          <element xid="ST03">
            <data_ele>1705</data_ele>
            <name>Version, Release, or Industry Identifier</name>
            <usage>R</usage>
            <seq>03</seq>
            <valid_codes>
              <code>005010X214</code>
            </valid_codes>
          </element>
        </segment>
              <!--End of ST segment-->
              <loop xid="HEADER" type="wrapper">
          <name>Header</name>
          <usage>R</usage>
          <pos>0100</pos>
          <repeat>1</repeat>
          <segment xid="BHT">
            <name>Beginning of Hierarchical Transaction</name>
            <usage>R</usage>
            <pos>0200</pos>
            <max_use>1</max_use>
            <element xid="BHT01">
              <data_ele>1005</data_ele>
              <name>Hierarchical Structure Code</name>
              <usage>R</usage>
              <seq>01</seq>
              <valid_codes>
                <code>0085</code>
              </valid_codes>
            </element>
            <element xid="BHT02">
              <data_ele>353</data_ele>
              <name>Transaction Set Purpose Code</name>
              <usage>R</usage>
              <seq>02</seq>
              <valid_codes>
                <code>08</code>
              </valid_codes>
            </element>
            <element xid="BHT03">
              <data_ele>127</data_ele>
              <name>Originator Application Transaction Identifier</name>
              <usage>R</usage>
              <seq>03</seq>
            </element>
            <element xid="BHT04">
              <data_ele>373</data_ele>
              <name>Transaction Set Creation Date</name>
              <usage>R</usage>
              <seq>04</seq>
            </element>
            <element xid="BHT05">
              <data_ele>337</data_ele>
              <name>Transaction Set Creation Time</name>
              <usage>R</usage>
              <seq>05</seq>
            </element>
            <element xid="BHT06">
              <data_ele>640</data_ele>
              <name>Transaction Type Code</name>
              <usage>R</usage>
              <seq>06</seq>
              <valid_codes>
                <code>TH</code>
              </valid_codes>
            </element>
          </segment>
                  <!--End of BHT segment-->
        </loop>
